name: Unit tests for front-end

on:
  push:
    branches:
      - "**"

jobs:
  build-test:
    name: Unit tests (front)
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run Jasmine tests
        env:
          CHROME_BIN: "/usr/bin/google-chrome"
        run: npm test --code-coverage

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-results
          path: front/test-results/test-results.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: front/coverage/
