name: Front-end

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-test:
    name: unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Jasmine tests
        run: npm run test -- --no-watch --code-coverage

      - name: Publish Jasmine coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jasmine-report
          path: front/coverage/bobapp/*
